# -*- mode: ruby -*-
  # vi: set ft=ruby :

  Vagrant.configure(2) do |config|
  config.vm.box = "nritholtz/ubuntu-14.04.1"
  config.vm.hostname = "Teamscale-DEMO-VM"

  #Display settings
  config.vm.provider "virtualbox" do |vb|
    #Display the VirtualBox GUI when booting the machine
    vb.gui = true
  
    # Customize the amount of memory on the VM and disable USB
    vb.memory = "2048"
    vb.name = "teamscale"
    vb.customize ["modifyvm", :id, "--clipboard", "bidirectional"]
    vb.customize ["modifyvm", :id, "--usb", "off"]
    vb.customize ["modifyvm", :id, "--usbehci", "off"]
  end
	
  #Provisions to be added to the VM

  config.vm.provision "shell", privileged: false, inline: <<-SHELL 
	#ubuntu update and install desktop
	sudo apt-get update -y
	
	# Remove unwanted icons from Launcher
        cd /usr/share/applications && sudo rm -f libreoffice-writer.desktop libreoffice-calc.desktop libreoffice-impress.desktop ubuntu-software-center.desktop ubuntu-amazon-default.desktop

	#java, maven and eclipse install
	sudo echo oracle-java8-installer shared/accepted-oracle-license-v1-1 select true | sudo /usr/bin/debconf-set-selections
	sudo add-apt-repository ppa:webupd8team/java -y
	sudo apt-get install oracle-java8-installer -y
	sudo wget --no-check-certificate https://github.com/aglover/ubuntu-equip/raw/master/equip_java8.sh && bash equip_java8.sh
	sudo apt-get install maven -y
	sudo wget -O /opt/eclipse-java-luna-SR2-linux-gtk.tar.gz http://ftp.fau.de/eclipse/technology/epp/downloads/release/luna/SR2/eclipse-java-luna-SR2-linux-gtk.tar.gz
        cd /opt/ && sudo tar -zxvf eclipse-*.tar.gz

	#teamscale installation
	sudo wget -O /home/vagrant/teamscale-v1.6.0.zip https://www.cqse.eu/download/teamscale/teamscale-v1.6.0.zip
	unzip /home/vagrant/teamscale-v1.6.0.zip -d /home/vagrant/Desktop/teamscale-v1.6.0
	wget -O /home/vagrant/Desktop/teamscale-v1.6.0/teamscale/teamscale.license https://raw.githubusercontent.com/SoftwareEngineeringToolDemos/ICSE-2014-Teamscale/master/build-vm/teamscale.license
	
	#extract VM files to desktop
	sudo chmod 777 /vagrant/*
	sudo cp /vagrant/*.jar /opt/eclipse/plugins/
        unzip /vagrant/Teamscale_VM_Desktop_Files.zip -d /home/vagrant/Desktop/
        chmod +x /home/vagrant/Desktop/*.desktop

	# Import spring-petclinic Project to Eclipse
        mkdir /home/vagrant/workspace/
	sudo apt-get install git -y
	cd /home/vagrant/ && git clone https://github.com/spring-projects/spring-petclinic.git
	cd /home/vagrant/spring-petclinic/ && mvn eclipse:eclipse
	
	# Add Eclipse to startup applications before reloading VM
	sudo chfn -f "vagrant" vagrant
        mkdir -p /home/vagrant/.config/autostart/
        cp /home/vagrant/Desktop/Eclipse.desktop /home/vagrant/.config/autostart/
	mv /home/vagrant/Desktop/teamscale*.desktop /home/vagrant/.config/autostart/

  SHELL
  
  config.vm.provision :reload
	
end
